version: '3.7'
services:
##############################################################################################
####################################### data Service###########################################
##############################################################################################
   mqtt-broker:
      image: 172.21.32.31:5000/eclipse-mosquitto:1.4.12
      restart: always
      ports:
      - 1883:1883
      deploy:
         replicas: 1
         placement:
            constraints:
            - node.role==manager
            - node.labels.hostname==dbs-server106
   mysql:
      image: 172.21.32.31:5000/mysql-canal:5.7.22
      container_name: mysql
      restart: always
      privileged: true
      environment:
      - MYSQL_ROOT_PASSWORD=SqlPwd1@
      volumes:
      - /opt/deploy/data/mysql/data:/var/lib/mysql
      ports:
      - 3306:3306
      deploy:
         replicas: 1
         placement:
            constraints:
            - node.role==manager
            - node.labels.hostname==dbs-server106
   mysql3307:
      image: 172.21.32.31:5000/mysqld:5.7.27
      restart: always
      privileged: true
      environment:
      - MYSQL_ROOT_PASSWORD=MysqlPwd1@
      volumes:
      - /opt/deploy/data/mysql3307/data:/var/lib/mysql
      ports:
      - 3307:3306
      deploy:
         replicas: 1
         placement:
            constraints:
            - node.role==manager
            - node.labels.hostname==dbs-server106
   mysql3308:
      image: 172.21.32.31:5000/mysqld:5.7.27
      restart: always
      privileged: true
      environment:
      - MYSQL_ROOT_PASSWORD=SqlPwd1@
      volumes:
      - /opt/deploy/data/mysql3308/data:/var/lib/mysql
      ports:
      - 3308:3306
      deploy:
         replicas: 1
         placement:
            constraints:
            - node.role==manager
            - node.labels.hostname==dbs-server106
   phpmyadmin:
      image: 172.21.32.31:5000/phpmyadmin/phpmyadmin:4.8.1
      restart: always
      depends_on:
      - mysql
      environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      ports:
      - 30680:80
      deploy:
         replicas: 1
         placement:
            constraints:
            - node.role==manager
            - node.labels.hostname==dbs-server106
   phpmyadmin3307:
      image: 172.21.32.31:5000/phpmyadmin/phpmyadmin:4.8.1
      restart: always
      depends_on:
      - mysql3307
      environment:
      - PMA_HOST=mysql3307
      - PMA_PORT=3306
      ports:
      - 30780:80
      deploy:
         replicas: 1
         placement:
            constraints:
            - node.role==manager
            - node.labels.hostname==dbs-server106
   redis:
      image: 172.21.32.31:5000/redis:4.0.9-alpine
      restart: always
      volumes:
      - /opt/deploy/data/redis-data:/data
      ports:
      - 6379:6379
      deploy:
         replicas: 1
         placement:
            constraints:
            - node.role==manager
            - node.labels.hostname==dbs-server106
   redis-auth:
      image: 172.21.32.31:5000/redis:4.0.9-alpine
      restart: always
      ports:
      - 6399:6379
      deploy:
         replicas: 1
         placement:
            constraints:
            - node.role==manager
            - node.labels.hostname==dbs-server106
   redis-message:
      image: 172.21.32.31:5000/redis:4.0.9-alpine
      restart: always
      volumes:
      - /opt/deploy/data/redis-message-data:/data
      ports:
      - 6389:6379
      deploy:
         replicas: 1
         placement:
            constraints:
            - node.role==manager
            - node.labels.hostname==dbs-server110
   neo4j:
      image: 172.21.32.31:5000/neo4j:3.4
      restart: always
      volumes:
      - /opt/deploy/data/neo4j_data:/data
      ports:
      - 7687:7687
      - 7474:7474
      deploy:
         replicas: 1
         placement:
            constraints:
            - node.role==manager
            - node.labels.hostname==dbs-server106
   influxdb:
      image: 172.21.32.31:5000/influxdb:1.5.4-alpine
      restart: always
      volumes:
      - /opt/deploy/data/influxdb:/var/lib/influxdb
      ports:
      - 8086:8086
      deploy:
         replicas: 1
         placement:
            constraints:
            - node.role==manager
            - node.labels.hostname==dbs-server106
   canal-server:
      image: 172.21.32.31:5000/canal/canal-server:v1.1.3
      restart: always
      volumes:
      - /opt/deploy/data/canal/server:/home/admin/canal-server/conf
      - /etc/localtime:/etc/localtime
      ports:
      - 11111:11111
      deploy:
         replicas: 1
         placement:
            constraints:
            - node.role==manager
            - node.labels.hostname==dbs-server106
   node-red-01:
      image: 172.21.32.31:5000/hollysys-node-red:1.0.0
      restart: always
      privileged: true
      volumes:
      - /opt/deploy/data/node-red-data-01:/data
      ports:
      - 18800:1880
      deploy:
         replicas: 1
         placement:
            constraints:
            - node.role==manager
            - node.labels.hostname==dbs-server106
   node-red-02:
      image: 172.21.32.31:5000/hollysys-node-red:1.0.0
      restart: always
      privileged: true
      volumes:
      - /opt/deploy/data/node-red-data-02:/data
      ports:
      - 18801:1880
      deploy:
         replicas: 1
         placement:
            constraints:
            - node.role==manager
            - node.labels.hostname==dbs-server106
   node-red-03:
      image: 172.21.32.31:5000/hollysys-node-red:1.0.0
      restart: always
      privileged: true
      volumes:
      - /opt/deploy/data/node-red-data-03:/data
      ports:
      - 18802:1880
      deploy:
         replicas: 1
         placement:
            constraints:
            - node.role==manager
            - node.labels.hostname==dbs-server106
   node-red-04:
      image: 172.21.32.31:5000/hollysys-node-red:1.0.0
      restart: always
      privileged: true
      volumes:
      - /opt/deploy/data/node-red-data-04:/data
      ports:
      - 18804:1880
      deploy:
         replicas: 1
         placement:
            constraints:
            - node.role==manager
            - node.labels.hostname==dbs-server106
   node-red-05:
      image: 172.21.32.31:5000/hollysys-node-red:1.0.0
      restart: always
      privileged: true
      volumes:
      - /opt/deploy/data/node-red-data-05:/data
      ports:
      - 18805:1880
      deploy:
         replicas: 1
         placement:
            constraints:
            - node.role==manager
            - node.labels.hostname==dbs-server106
   node-red-06:
      image: 172.21.32.31:5000/hollysys-node-red:1.0.0
      restart: always
      privileged: true
      volumes:
      - /opt/deploy/data/node-red-data-06:/data
      ports:
      - 18806:1880
      deploy:
         replicas: 1
         placement:
            constraints:
            - node.role==manager
            - node.labels.hostname==dbs-server106
   node-red-07:
      image: 172.21.32.31:5000/hollysys-node-red:1.0.0
      restart: always
      privileged: true
      volumes:
      - /opt/deploy/data/node-red-data-07:/data
      ports:
      - 18807:1880
      deploy:
         replicas: 1
         placement:
            constraints:
            - node.role==manager
            - node.labels.hostname==dbs-server106
   node-red-08:
      image: 172.21.32.31:5000/hollysys-node-red:1.0.0
      restart: always
      privileged: true
      volumes:
      - /opt/deploy/data/node-red-data-08:/data
      ports:
      - 18808:1880
      deploy:
         replicas: 1
         placement:
            constraints:
            - node.role==manager
            - node.labels.hostname==dbs-server106
   registry-ui:
      image: 172.21.32.31:5000/jc21/registry-ui:2.0.2
      restart: always
      environment:
      - REGISTRY_HOST=172.21.32.31:5000
      ports:
      - 30080:80
      deploy:
         replicas: 1
         placement:
            constraints:
            - node.role==manager
            - node.labels.hostname==dbs-server106
##############################################################################################
####################################### App Service###########################################
##############################################################################################
   xxl-job-admin:
      image: 172.21.32.31:5000/xxl-job-admin:2.1.0
      restart: always
      environment:
      - NETWORK_NAME=eth0
      volumes:
      - /opt/deploy/conf/xxl-job-admin:/opt/deploy/xxl-job-admin/config
      ports:
      - 7072:7072
      depends_on:
      - mysql3307
      logging:
         driver: json-file
         options:
            max-size: 10m
            max-file: '5'
      deploy:
         replicas: 1
   sf-modelmanager-service:
      image: 172.21.32.31:5000/sf-modelmanager-service:1.0.0
      restart: always
      environment:
      - NETWORK_NAME=eth0
      volumes:
      - /opt/deploy/conf/sf-modelmanager-service:/opt/deploy/sf-modelmanager-service/config
      - /etc/localtime:/etc/localtime
      ports:
      - 8170:8170
      depends_on:
      - neo4j
      logging:
         driver: json-file
         options:
            max-size: 10m
            max-file: '5'
      deploy:
         replicas: 1
   sf-gatewayproxy-service:
      image: 172.21.32.31:5000/sf-gatewayproxy-service:1.0.0
      restart: always
      environment:
      - NETWORK_NAME=eth0
      volumes:
      - /opt/deploy/conf/sf-gatewayproxy-service:/opt/deploy/sf-gatewayproxy-service/config
      - /etc/localtime:/etc/localtime
      ports:
      - 8177:8177
      depends_on:
      - neo4j
      - redis
      logging:
         driver: json-file
         options:
            max-size: 10m
            max-file: '5'
      deploy:
         replicas: 1
   sf-history-service:
      image: 172.21.32.31:5000/sf-history-service:1.0.0
      restart: always
      environment:
      - NETWORK_NAME=eth0
      volumes:
      - /opt/deploy/conf/sf-history-service:/opt/deploy/sf-history-service/config
      - /etc/localtime:/etc/localtime
      ports:
      - 8140:8140
      depends_on:
      - influxdb
      - redis
      - neo4j
      - sf-modelmanager-service
      logging:
         driver: json-file
         options:
            max-size: 10m
            max-file: '5'
      deploy:
         replicas: 1
   sf-realtime-service:
      image: 172.21.32.31:5000/sf-realtime-service:1.0.0
      restart: always
      environment:
      - NETWORK_NAME=eth0
      volumes:
      - /opt/deploy/conf/sf-realtime-service:/opt/deploy/sf-realtime-service/config
      - /etc/localtime:/etc/localtime
      ports:
      - 8272:8172
      depends_on:
      - redis
      - neo4j
      logging:
         driver: json-file
         options:
            max-size: 10m
            max-file: '5'
      deploy:
         replicas: 6
   sf-realtime-route-service:
      image: 172.21.32.31:5000/sf-realtime-service:1.0.0
      restart: always
      environment:
      - NETWORK_NAME=eth0
      volumes:
      - /opt/deploy/conf/sf-realtime-route-service:/opt/deploy/sf-realtime-service/config
      - /etc/localtime:/etc/localtime
      ports:
      - 8172:8172
      depends_on:
      - redis
      - neo4j
      - canal-server
      logging:
         driver: json-file
         options:
            max-size: 10m
            max-file: '5'
      deploy:
         replicas: 1
   target-manager-service:
      image: 172.21.32.31:5000/target-manager-service:1.0.0
      restart: always
      environment:
      - NETWORK_NAME=eth0
      volumes:
      - /opt/deploy/conf/target-manager-service:/opt/deploy/target-manager-service/config
      - /etc/localtime:/etc/localtime
      ports:
      - 8631:8631
      depends_on:
      - sf-modelmanager-service
      logging:
         driver: json-file
         options:
            max-size: 10m
            max-file: '5'
      deploy:
         replicas: 1
   target-calculate-service:
      image: 172.21.32.31:5000/target-calculate-service:1.0.0
      restart: always
      environment:
      - NETWORK_NAME=eth0
      - DEBUG_VERBOSE=false
      volumes:
      - /opt/deploy/conf/target-calculate-service:/opt/deploy/target-calculate-service/config
      - /etc/localtime:/etc/localtime
      ports:
      - 8731:8731
      - 65534:65534
      depends_on:
      - mysql3307
      - sf-realtime-service
      - xxl-job-admin
      logging:
         driver: json-file
         options:
            max-size: 10m
            max-file: '5'
      deploy:
         replicas: 1
   target-calculate-label-service:
      image: 172.21.32.31:5000/target-calculate-service:1.0.0
      restart: always
      environment:
      - NETWORK_NAME=eth0
      - DEBUG_VERBOSE=false
      volumes:
      - /opt/deploy/conf/target-calculate-label-service:/opt/deploy/target-calculate-service/config
      - /etc/localtime:/etc/localtime
      ports:
      - 9731:8731
      - 55534:65534
      depends_on:
      - mysql3307
      - sf-realtime-service
      logging:
         driver: json-file
         options:
            max-size: 10m
            max-file: '5'
      deploy:
         replicas: 21
   target-calculate-route-service:
      image: 172.21.32.31:5000/target-calculate-service:1.0.0
      restart: always
      environment:
      - NETWORK_NAME=eth0
      - DEBUG_VERBOSE=false
      volumes:
      - /opt/deploy/conf/target-calculate-route-service:/opt/deploy/target-calculate-service/config
      - /etc/localtime:/etc/localtime
      ports:
      - 6731:8731
      - 45534:65534
      depends_on:
      - mysql3307
      - sf-realtime-service
      logging:
         driver: json-file
         options:
            max-size: 10m
            max-file: '5'
      deploy:
         replicas: 1
   target-calculate-job-service:
      image: 172.21.32.31:5000/target-calculate-service:1.0.0
      restart: always
      environment:
      - NETWORK_NAME=eth0
      - DEBUG_VERBOSE=false
      volumes:
      - /opt/deploy/conf/target-calculate-job-service:/opt/deploy/target-calculate-service/config
      - /etc/localtime:/etc/localtime
      ports:
      - 7731:8731
      - 35534:65534
      depends_on:
      - mysql3307
      - sf-realtime-service
      - xxl-job-admin
      logging:
         driver: json-file
         options:
            max-size: 10m
            max-file: '5'
      deploy:
         replicas: 1
   system-authority-service:
      image: 172.21.32.31:5000/authority:1.0.0
      restart: always
      environment:
      - NETWORK_NAME=eth0
      depends_on:
      - redis
      - mysql3308
      volumes:
      - /opt/deploy/conf/system-authority-service:/opt/deploy/authority/config
      - /etc/localtime:/etc/localtime
      ports:
      - 8551:8551
      deploy:
         replicas: 1
   system-manager-service:
      image: 172.21.32.31:5000/system-manager:1.0.0
      restart: always
      environment:
      - NETWORK_NAME=eth0
      depends_on:
      - mysql3308
      volumes:
      - /opt/deploy/conf/system-manager-service:/opt/deploy/system-manager/config
      - /etc/localtime:/etc/localtime
      ports:
      - 8571:8571
      deploy:
         replicas: 1
   dbs-decision-system-web:
      image: 172.21.32.31:5000/dbs-decision-system-web:1.0.0
      restart: always
      volumes:
      - /opt/deploy/conf/vue-web:/usr/share/nginx/html/config:ro
      - /etc/localtime:/etc/localtime
      ports:
      - 8080:80
      deploy:
         replicas: 1
   dbs-cockpit-web:
      image: 172.21.32.31:5000/dbs-cockpit-web:1.0.0
      restart: always
      volumes:
      - /opt/deploy/conf/vue-web:/usr/share/nginx/html/config:ro
      - /etc/localtime:/etc/localtime
      ports:
      - 7070:80
      deploy:
         replicas: 1
   target-manager-web:
      image: 172.21.32.31:5000/target-manager-web:1.0.0
      restart: always
      volumes:
      - /opt/deploy/conf/vue-web:/usr/share/nginx/html/config:ro
      - /etc/localtime:/etc/localtime
      ports:
      - 9090:80
      deploy:
         replicas: 1
   system-authority-web:
      image: 172.21.32.31:5000/authority-web:1.0.0
      restart: always
      volumes:
      - /opt/deploy/conf/vue-web:/usr/share/nginx/html/config:ro
      - /etc/localtime:/etc/localtime
      ports:
      - 8550:80
      deploy:
         replicas: 1
   system-manager-web:
      image: 172.21.32.31:5000/system-manager-web:1.0.0
      restart: always
      volumes:
      - /opt/deploy/conf/vue-web:/usr/share/nginx/html/config:ro
      - /etc/localtime:/etc/localtime
      ports:
      - 8570:80
      deploy:
         replicas: 1