version: '3.7'
services:
   zookeeper-1:
      image: zookeeper:3.5.5
      restart: always
      environment:
         ZOO_MY_ID: 1
         ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zookeeper-2:2888:3888;2181 server.3=zookeeper-3:2888:3888;2181
      volumes:
      - /opt/deploy/data/zookeeper/data:/data
      - /opt/deploy/data/zookeeper/datalog:/datalog
      - /opt/deploy/data/zookeeper/logs:/logs
      - /etc/localtime:/etc/localtime
      ports:
      - 2181:2181
      deploy:
         mode: global
         placement:
            constraints:
            - node.role==manager
            - node.labels.hostname==dbs-server131
   zookeeper-2:
      image: zookeeper:3.5.5
      restart: always
      environment:
         ZOO_MY_ID: 2
         ZOO_SERVERS: server.1=zookeeper-1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zookeeper-3:2888:3888;2181
      volumes:
      - /opt/deploy/data/zookeeper/data:/data
      - /opt/deploy/data/zookeeper/datalog:/datalog
      - /opt/deploy/data/zookeeper/logs:/logs
      - /etc/localtime:/etc/localtime
      ports:
      - 2182:2181
      deploy:
         mode: global
         placement:
            constraints:
            - node.role==manager
            - node.labels.hostname==dbs-server132
   zookeeper-3:
      image: zookeeper:3.5.5
      restart: always
      environment:
         ZOO_MY_ID: 3
         ZOO_SERVERS: server.1=zookeeper-1:2888:3888;2181 server.2=zookeeper-2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
      volumes:
      - /opt/deploy/data/zookeeper/data:/data
      - /opt/deploy/data/zookeeper/datalog:/datalog
      - /opt/deploy/data/zookeeper/logs:/logs
      - /etc/localtime:/etc/localtime
      ports:
      - 2183:2181
      deploy:
         mode: global
         placement:
            constraints:
            - node.role==manager
            - node.labels.hostname==dbs-server130
   kafka-1:
      image: wurstmeister/kafka:2.12-2.2.0
      restart: always
      environment:
         BROKER_ID_COMMAND: "echo 1"
         HOSTNAME_COMMAND: "ifconfig -a|grep inet|grep -v 127.0.0.1|grep -v 0.0.0.0|grep -v inet6|grep 10.0|awk '{print $$2}'|tr -d 'addr:'"
         KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:19092
         KAFKA_ADVERTISED_LISTENERS: INSIDE://_{HOSTNAME_COMMAND}:9092,OUTSIDE://172.21.32.131:19092
         KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
         KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
         KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
         KAFKA_LOG_DIRS: "/kafka/data"
         KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
         KAFKA_ZOOKEEPER_CONNECT_TIMEOUT_MS: 60000
         KAFKA_SOCKET_SEND_BUFFER_BYTES: 104857600
         KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 104857600
         KAFKA_SOCKET_REQUEST_MAX_BYTES: 104857600
         KAFKA_REPLICA_FETCH_MAX_BYTES: 104857600
         KAFKA_QUOTA_PRODUCER_DEFAULT: 104857600
         KAFKA_QUOTA_CONSUMER_DEFAULT: 104857600
      volumes:
      # - /opt/deploy/data/kafka/conf/server.properties:/opt/kafka/config/server.properties
      - /opt/deploy/data/kafka/data:/kafka/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime
      ports:
       - target: 19092
         published: 19092
         protocol: tcp
         mode: host
      depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
      deploy:
         mode: global
         placement:
            constraints:
            - node.role==manager
            - node.labels.hostname==dbs-server131
            preferences:
            - spread: node.labels.kafka
   kafka-2:
      image: wurstmeister/kafka:2.12-2.2.0
      restart: always
      environment:
         BROKER_ID_COMMAND: "echo 2"
         HOSTNAME_COMMAND: "ifconfig -a|grep inet|grep -v 127.0.0.1|grep -v 0.0.0.0|grep -v inet6|grep 10.0|awk '{print $$2}'|tr -d 'addr:'"
         KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:29092
         KAFKA_ADVERTISED_LISTENERS: INSIDE://_{HOSTNAME_COMMAND}:9092,OUTSIDE://172.21.32.132:29092
         KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
         KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
         KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
         KAFKA_LOG_DIRS: "/kafka/data"
         KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
         KAFKA_ZOOKEEPER_CONNECT_TIMEOUT_MS: 60000
         KAFKA_SOCKET_SEND_BUFFER_BYTES: 104857600
         KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 104857600
         KAFKA_SOCKET_REQUEST_MAX_BYTES: 104857600
         KAFKA_REPLICA_FETCH_MAX_BYTES: 104857600
         KAFKA_QUOTA_PRODUCER_DEFAULT: 104857600
         KAFKA_QUOTA_CONSUMER_DEFAULT: 104857600
      volumes:
      # - /opt/deploy/data/kafka/conf/server.properties:/opt/kafka/config/server.properties
      - /opt/deploy/data/kafka/data:/kafka/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime
      ports:
       - target: 29092
         published: 29092
         protocol: tcp
         mode: host
      depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
      deploy:
         mode: global
         placement:
            constraints:
            - node.role==manager
            - node.labels.hostname==dbs-server132
            preferences:
            - spread: node.labels.kafka
   kafka-3:
      image: wurstmeister/kafka:2.12-2.2.0
      restart: always
      environment:
         BROKER_ID_COMMAND: "echo 3"
         HOSTNAME_COMMAND: "ifconfig -a|grep inet|grep -v 127.0.0.1|grep -v 0.0.0.0|grep -v inet6|grep 10.0|awk '{print $$2}'|tr -d 'addr:'"
         KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:39092
         KAFKA_ADVERTISED_LISTENERS: INSIDE://_{HOSTNAME_COMMAND}:9092,OUTSIDE://172.21.32.130:39092
         KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
         KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
         KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
         KAFKA_LOG_DIRS: "/kafka/data"
         KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
         KAFKA_ZOOKEEPER_CONNECT_TIMEOUT_MS: 60000
         KAFKA_SOCKET_SEND_BUFFER_BYTES: 104857600
         KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 104857600
         KAFKA_SOCKET_REQUEST_MAX_BYTES: 104857600
         KAFKA_REPLICA_FETCH_MAX_BYTES: 104857600
         KAFKA_QUOTA_PRODUCER_DEFAULT: 104857600
         KAFKA_QUOTA_CONSUMER_DEFAULT: 104857600
      volumes:
      # - /opt/deploy/data/kafka/conf/server.properties:/opt/kafka/config/server.properties
      - /opt/deploy/data/kafka/data:/kafka/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime
      ports:
       - target: 39092
         published: 39092
         protocol: tcp
         mode: host
      depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
      deploy:
         mode: global
         placement:
            constraints:
            - node.role==manager
            - node.labels.hostname==dbs-server130
            preferences:
            - spread: node.labels.kafka
   
   kafka-manager:
      image: kafkamanager/kafka-manager:2.0.0.2
      restart: always
      environment:
         ZK_HOSTS: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      volumes:
      - /etc/localtime:/etc/localtime
      ports:
      - 19000:9000
      deploy:
         mode: global
         placement:
            constraints:
            - node.role==manager
            - node.labels.hostname==dbs-server130