version: '3.7'
services:
##############################################################################################
####################################### data Service###########################################
##############################################################################################
   mqtt-broker:
      image: eclipse-mosquitto:1.4.12
      restart: always
      ports:
      - 1883:1883
      deploy:
         replicas: 1
   mysql:
      image: mysql-canal:5.7.22
      container_name: mysql
      restart: always
      privileged: true
      environment:
      - MYSQL_ROOT_PASSWORD=SqlPwd1@
      volumes:
      - /opt/deploy/data/mysql/data:/var/lib/mysql
      ports:
      - 3306:3306
      deploy:
         replicas: 1
   mysql3307:
      image: mysqld:5.7.27
      restart: always
      privileged: true
      environment:
      - MYSQL_ROOT_PASSWORD=MysqlPwd1@
      volumes:
      - /opt/deploy/data/mysql3307/data:/var/lib/mysql
      ports:
      - 3307:3306
      deploy:
         replicas: 1
   mysql3308:
      image: mysqld:5.7.27
      restart: always
      privileged: true
      environment:
      - MYSQL_ROOT_PASSWORD=SqlPwd1@
      volumes:
      - /opt/deploy/data/mysql3308/data:/var/lib/mysql
      ports:
      - 3308:3306
      deploy:
         replicas: 1
   phpmyadmin:
      image: phpmyadmin/phpmyadmin:4.8.1
      restart: always
      links:
      - mysql
      environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      ports:
      - 30680:80
      deploy:
         replicas: 1
   phpmyadmin3307:
      image: phpmyadmin/phpmyadmin:4.8.1
      restart: always
      links:
      - mysql3307
      environment:
      - PMA_HOST=mysql3307
      - PMA_PORT=3306
      ports:
      - 30780:80
      deploy:
         replicas: 1
   redis:
      image: redis:4.0.9-alpine
      restart: always
      volumes:
      - /opt/deploy/data/redis-data:/data
      ports:
      - 6379:6379
      deploy:
         replicas: 1
   redis-message:
      image: redis:4.0.9-alpine
      restart: always
      volumes:
      - /opt/deploy/data/redis-message-data:/data
      ports:
      - 6389:6379
      deploy:
         replicas: 1
   neo4j:
      image: neo4j:3.4
      restart: always
      volumes:
      - /opt/deploy/data/neo4j_data:/data
      ports:
      - 7687:7687
      - 7474:7474
      deploy:
         replicas: 1
   influxdb:
      image: influxdb:1.5.4-alpine
      restart: always
      volumes:
      - /opt/deploy/data/influxdb:/var/lib/influxdb
      ports:
      - 8086:8086
      deploy:
         replicas: 1
   canal-server:
      image: canal-server
      restart: always
      volumes:
      - /opt/deploy/data/canal-server-conf:/home/admin/canal-server/conf
      ports:
      - 11111:11111
      links:
      - mysql
      - mysql3307
      deploy:
         replicas: 1
   node-red-01:
      image: hollysys-node-red:1.0.0
      restart: always
      privileged: true
      volumes:
      - /opt/deploy/data/node-red-data-01:/data
      ports:
      - 18800:1880
      deploy:
         replicas: 1
   node-red-02:
      image: hollysys-node-red:1.0.0
      restart: always
      privileged: true
      volumes:
      - /opt/deploy/data/node-red-data-02:/data
      ports:
      - 18801:1880
      deploy:
         replicas: 1
   node-red-03:
      image: hollysys-node-red:1.0.0
      restart: always
      privileged: true
      volumes:
      - /opt/deploy/data/node-red-data-03:/data
      ports:
      - 18802:1880
      deploy:
         replicas: 1
   registry-ui:
      image: jc21/registry-ui:2.0.2
      restart: always
      environment:
      - REGISTRY_HOST=172.21.32.31:5000
      ports:
      - 30080:80
      deploy:
         replicas: 1
##############################################################################################
####################################### App Service###########################################
##############################################################################################
   xxl-job-admin:
      image: xxl-job-admin:2.1.0
      restart: always
      environment:
      - NETWORK_NAME=eth0
      volumes:
      - /opt/deploy/conf/xxl-job-admin-config:/opt/deploy/xxl-job-admin/config
      ports:
      - 7072:7072
      links:
      - mysql3307
      logging:
         driver: json-file
         options:
            max-size: 10m
            max-file: '5'
      deploy:
         replicas: 1
   sf-modelmanager-service:
      image: sf-modelmanager-service:1.0.0
      restart: always
      environment:
      - NETWORK_NAME=eth0
      volumes:
      - /opt/deploy/conf/sf-modelmanager-service-config:/opt/deploy/sf-modelmanager-service/config
      - /etc/localtime:/etc/localtime
      ports:
      - 8170:8170
      links:
      - neo4j
      logging:
         driver: json-file
         options:
            max-size: 10m
            max-file: '5'
      deploy:
         replicas: 1
   sf-gatewayproxy-service:
      image: sf-gatewayproxy-service:1.0.0
      restart: always
      environment:
      - NETWORK_NAME=eth0
      volumes:
      - /opt/deploy/conf/sf-gatewayproxy-service-config:/opt/deploy/sf-gatewayproxy-service/config
      - /etc/localtime:/etc/localtime
      ports:
      - 8177:8177
      links:
      - neo4j
      - redis
      logging:
         driver: json-file
         options:
            max-size: 10m
            max-file: '5'
      deploy:
         replicas: 1
   sf-history-service:
      image: sf-history-service:1.0.0
      restart: always
      environment:
      - NETWORK_NAME=eth0
      volumes:
      - /opt/deploy/conf/sf-history-service-config:/opt/deploy/sf-history-service/config
      - /etc/localtime:/etc/localtime
      ports:
      - 8140:8140
      links:
      - influxdb
      - redis
      - neo4j
      - sf-modelmanager-service
      logging:
         driver: json-file
         options:
            max-size: 10m
            max-file: '5'
      deploy:
         replicas: 1
   sf-realtime-service:
      image: sf-realtime-service:1.0.0
      restart: always
      environment:
      - NETWORK_NAME=eth0
      volumes:
      - /opt/deploy/conf/sf-realtime-service-config:/opt/deploy/sf-realtime-service/config
      - /etc/localtime:/etc/localtime
      ports:
      - 8272:8172
      links:
      - redis
      - neo4j
      - canal-server
      logging:
         driver: json-file
         options:
            max-size: 10m
            max-file: '5'
      deploy:
         replicas: 1
   sf-realtime-distribute-service:
      image: sf-realtime-service:1.0.0
      restart: always
      environment:
      - NETWORK_NAME=eth0
      volumes:
      - /opt/deploy/conf/sf-realtime-service-config1:/opt/deploy/sf-realtime-service/config
      - /etc/localtime:/etc/localtime
      ports:
      - 8172:8172
      links:
      - redis
      - neo4j
      logging:
         driver: json-file
         options:
            max-size: 10m
            max-file: '5'
      deploy:
         replicas: 21
   target-manager-service:
      image: target-manager-service:1.0.0
      restart: always
      environment:
      - NETWORK_NAME=eth0
      volumes:
      - /opt/deploy/conf/target-manager-service-config:/opt/deploy/target-manager-service/config
      - /etc/localtime:/etc/localtime
      ports:
      - 8631:8631
      links:
      - sf-modelmanager-service
      logging:
         driver: json-file
         options:
            max-size: 10m
            max-file: '5'
      deploy:
         replicas: 1
   target-calculate-service:
      image: target-calculate-service:1.0.0
      restart: always
      environment:
      - NETWORK_NAME=eth0
      - DEBUG_VERBOSE=false
      volumes:
      - /opt/deploy/conf/target-calculate-service-config:/opt/deploy/target-calculate-service/config
      - /etc/localtime:/etc/localtime
      ports:
      - 8731:8731
      - 65534:65534
      links:
      - mysql3307
      - sf-realtime-service
      logging:
         driver: json-file
         options:
            max-size: 10m
            max-file: '5'
      deploy:
         replicas: 1
   target-calculate-label-service:
      image: target-calculate-service:1.0.0
      restart: always
      environment:
      - NETWORK_NAME=eth0
      - DEBUG_VERBOSE=false
      volumes:
      - /opt/deploy/conf/target-calculate-service-config1:/opt/deploy/target-calculate-service/config
      - /etc/localtime:/etc/localtime
      ports:
      - 9731:8731
      - 55534:65534
      links:
      - mysql3307
      - sf-realtime-service
      logging:
         driver: json-file
         options:
            max-size: 10m
            max-file: '5'
      deploy:
         replicas: 5
   target-calculate-labelX-service:
      image: target-calculate-service:1.0.0
      restart: always
      environment:
      - NETWORK_NAME=eth0
      - DEBUG_VERBOSE=false
      volumes:
      - /opt/deploy/conf/target-calculate-service-config11:/opt/deploy/target-calculate-service/config
      - /etc/localtime:/etc/localtime
      ports:
      - 6731:8731
      - 45534:65534
      links:
      - mysql3307
      - sf-realtime-service
      logging:
         driver: json-file
         options:
            max-size: 10m
            max-file: '5'
      deploy:
         replicas: 1
   target-calculate-job-service:
      image: target-calculate-service:1.0.0
      restart: always
      environment:
      - NETWORK_NAME=eth0
      - DEBUG_VERBOSE=false
      volumes:
      - /opt/deploy/conf/target-calculate-service-config2:/opt/deploy/target-calculate-service/config
      - /etc/localtime:/etc/localtime
      ports:
      - 7731:8731
      - 35534:65534
      links:
      - mysql3307
      - sf-realtime-service
      logging:
         driver: json-file
         options:
            max-size: 10m
            max-file: '5'
      deploy:
         replicas: 21
   system-authority-service:
      image: authority:1.0.0
      restart: always
      environment:
      - NETWORK_NAME=eth0
      links:
      - redis
      - mysql3308
      volumes:
      - /opt/deploy/conf/authority-config:/opt/deploy/authority/config
      - /etc/localtime:/etc/localtime
      ports:
      - 8551:8551
      deploy:
         replicas: 1
   system-manager-service:
      image: system-manager:1.0.0
      restart: always
      environment:
      - NETWORK_NAME=eth0
      links:
      - mysql3308
      volumes:
      - /opt/deploy/conf/system-manager-config:/opt/deploy/system-manager/config
      - /etc/localtime:/etc/localtime
      ports:
      - 8571:8571
      deploy:
         replicas: 1
   dbs-decision-system-web:
      image: dbs-decision-system-web:1.0.0
      restart: always
      volumes:
      - /opt/deploy/conf/web-config:/usr/share/nginx/html/config:ro
      - /etc/localtime:/etc/localtime
      ports:
      - 8080:80
      deploy:
         replicas: 1
   dbs-cockpit-web:
      image: dbs-cockpit-web:1.0.0
      restart: always
      volumes:
      - /opt/deploy/conf/web-config:/usr/share/nginx/html/config:ro
      - /etc/localtime:/etc/localtime
      ports:
      - 7070:80
      deploy:
         replicas: 1
   target-manager-web:
      image: target-manager-web:1.0.0
      restart: always
      volumes:
      - /opt/deploy/conf/web-config:/usr/share/nginx/html/config:ro
      - /etc/localtime:/etc/localtime
      ports:
      - 9090:80
      deploy:
         replicas: 1
   system-authority-web:
      image: authority-web:1.0.0
      restart: always
      volumes:
      - /opt/deploy/conf/web-config:/usr/share/nginx/html/config:ro
      - /etc/localtime:/etc/localtime
      ports:
      - 8550:80
      deploy:
         replicas: 1
   system-manager-web:
      image: system-manager-web:1.0.0
      restart: always
      volumes:
      - /opt/deploy/conf/web-config:/usr/share/nginx/html/config:ro
      - /etc/localtime:/etc/localtime
      ports:
      - 8570:80
      deploy:
         replicas: 1